/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model;


import ch.uzh.slamer.model.tables.Address;
import ch.uzh.slamer.model.tables.Penalty;
import ch.uzh.slamer.model.tables.ServiceLevelObjective;
import ch.uzh.slamer.model.tables.Sla;
import ch.uzh.slamer.model.tables.SlaUser;
import ch.uzh.slamer.model.tables.SloType;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = -1594111469;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.address</code>.
     */
    public final Address ADDRESS = ch.uzh.slamer.model.tables.Address.ADDRESS;

    /**
     * The table <code>public.penalty</code>.
     */
    public final Penalty PENALTY = ch.uzh.slamer.model.tables.Penalty.PENALTY;

    /**
     * The table <code>public.service_level_objective</code>.
     */
    public final ServiceLevelObjective SERVICE_LEVEL_OBJECTIVE = ch.uzh.slamer.model.tables.ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE;

    /**
     * The table <code>public.sla</code>.
     */
    public final Sla SLA = ch.uzh.slamer.model.tables.Sla.SLA;

    /**
     * The table <code>public.sla_user</code>.
     */
    public final SlaUser SLA_USER = ch.uzh.slamer.model.tables.SlaUser.SLA_USER;

    /**
     * The table <code>public.slo_type</code>.
     */
    public final SloType SLO_TYPE = ch.uzh.slamer.model.tables.SloType.SLO_TYPE;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ADDRESS_ID_SEQ,
            Sequences.PENALTY_ID_SEQ,
            Sequences.SERVICE_LEVEL_OBJECTIVE_ID_SEQ,
            Sequences.SLA_ID_SEQ,
            Sequences.SLA_USER_ID_SEQ,
            Sequences.SLO_TYPE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Address.ADDRESS,
            Penalty.PENALTY,
            ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE,
            Sla.SLA,
            SlaUser.SLA_USER,
            SloType.SLO_TYPE);
    }
}
