/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model;


import ch.uzh.slamer.model.tables.Address;
import ch.uzh.slamer.model.tables.Penalty;
import ch.uzh.slamer.model.tables.ServiceLevelObjective;
import ch.uzh.slamer.model.tables.Sla;
import ch.uzh.slamer.model.tables.SlaUser;
import ch.uzh.slamer.model.tables.SloType;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in public
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.address</code>.
     */
    public static final Address ADDRESS = ch.uzh.slamer.model.tables.Address.ADDRESS;

    /**
     * The table <code>public.penalty</code>.
     */
    public static final Penalty PENALTY = ch.uzh.slamer.model.tables.Penalty.PENALTY;

    /**
     * The table <code>public.service_level_objective</code>.
     */
    public static final ServiceLevelObjective SERVICE_LEVEL_OBJECTIVE = ch.uzh.slamer.model.tables.ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE;

    /**
     * The table <code>public.sla</code>.
     */
    public static final Sla SLA = ch.uzh.slamer.model.tables.Sla.SLA;

    /**
     * The table <code>public.sla_user</code>.
     */
    public static final SlaUser SLA_USER = ch.uzh.slamer.model.tables.SlaUser.SLA_USER;

    /**
     * The table <code>public.slo_type</code>.
     */
    public static final SloType SLO_TYPE = ch.uzh.slamer.model.tables.SloType.SLO_TYPE;
}
