/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Address implements Serializable {

    private static final long serialVersionUID = -2126355597;

    private Integer id;
    private Integer postalCode;
    private String  city;
    private String  street;
    private Integer streetNr;
    private Integer userId;

    public Address() {}

    public Address(Address value) {
        this.id = value.id;
        this.postalCode = value.postalCode;
        this.city = value.city;
        this.street = value.street;
        this.streetNr = value.streetNr;
        this.userId = value.userId;
    }

    public Address(
        Integer id,
        Integer postalCode,
        String  city,
        String  street,
        Integer streetNr,
        Integer userId
    ) {
        this.id = id;
        this.postalCode = postalCode;
        this.city = city;
        this.street = street;
        this.streetNr = streetNr;
        this.userId = userId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getPostalCode() {
        return this.postalCode;
    }

    public void setPostalCode(Integer postalCode) {
        this.postalCode = postalCode;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getStreet() {
        return this.street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public Integer getStreetNr() {
        return this.streetNr;
    }

    public void setStreetNr(Integer streetNr) {
        this.streetNr = streetNr;
    }

    public Integer getUserId() {
        return this.userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Address (");

        sb.append(id);
        sb.append(", ").append(postalCode);
        sb.append(", ").append(city);
        sb.append(", ").append(street);
        sb.append(", ").append(streetNr);
        sb.append(", ").append(userId);

        sb.append(")");
        return sb.toString();
    }
}
