/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceLevelObjective implements Serializable {

    private static final long serialVersionUID = -331773820;

    private Integer    id;
    private String     name;
    private Date       validFrom;
    private Date       validTo;
    private Integer    slaId;
    private String     timeUnit;
    private String     relationalOperator;
    private Integer    sloTypeId;
    private BigDecimal percentageOfAvailability;
    private String     throughputDataUnit;
    private BigDecimal throughputDataSize;
    private BigDecimal throughputThresholdValue;
    private BigDecimal averageResponseTimeValue;

    public ServiceLevelObjective() {}

    public ServiceLevelObjective(ServiceLevelObjective value) {
        this.id = value.id;
        this.name = value.name;
        this.validFrom = value.validFrom;
        this.validTo = value.validTo;
        this.slaId = value.slaId;
        this.timeUnit = value.timeUnit;
        this.relationalOperator = value.relationalOperator;
        this.sloTypeId = value.sloTypeId;
        this.percentageOfAvailability = value.percentageOfAvailability;
        this.throughputDataUnit = value.throughputDataUnit;
        this.throughputDataSize = value.throughputDataSize;
        this.throughputThresholdValue = value.throughputThresholdValue;
        this.averageResponseTimeValue = value.averageResponseTimeValue;
    }

    public ServiceLevelObjective(
        Integer    id,
        String     name,
        Date       validFrom,
        Date       validTo,
        Integer    slaId,
        String     timeUnit,
        String     relationalOperator,
        Integer    sloTypeId,
        BigDecimal percentageOfAvailability,
        String     throughputDataUnit,
        BigDecimal throughputDataSize,
        BigDecimal throughputThresholdValue,
        BigDecimal averageResponseTimeValue
    ) {
        this.id = id;
        this.name = name;
        this.validFrom = validFrom;
        this.validTo = validTo;
        this.slaId = slaId;
        this.timeUnit = timeUnit;
        this.relationalOperator = relationalOperator;
        this.sloTypeId = sloTypeId;
        this.percentageOfAvailability = percentageOfAvailability;
        this.throughputDataUnit = throughputDataUnit;
        this.throughputDataSize = throughputDataSize;
        this.throughputThresholdValue = throughputThresholdValue;
        this.averageResponseTimeValue = averageResponseTimeValue;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getValidFrom() {
        return this.validFrom;
    }

    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    public Date getValidTo() {
        return this.validTo;
    }

    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }

    public Integer getSlaId() {
        return this.slaId;
    }

    public void setSlaId(Integer slaId) {
        this.slaId = slaId;
    }

    public String getTimeUnit() {
        return this.timeUnit;
    }

    public void setTimeUnit(String timeUnit) {
        this.timeUnit = timeUnit;
    }

    public String getRelationalOperator() {
        return this.relationalOperator;
    }

    public void setRelationalOperator(String relationalOperator) {
        this.relationalOperator = relationalOperator;
    }

    public Integer getSloTypeId() {
        return this.sloTypeId;
    }

    public void setSloTypeId(Integer sloTypeId) {
        this.sloTypeId = sloTypeId;
    }

    public BigDecimal getPercentageOfAvailability() {
        return this.percentageOfAvailability;
    }

    public void setPercentageOfAvailability(BigDecimal percentageOfAvailability) {
        this.percentageOfAvailability = percentageOfAvailability;
    }

    public String getThroughputDataUnit() {
        return this.throughputDataUnit;
    }

    public void setThroughputDataUnit(String throughputDataUnit) {
        this.throughputDataUnit = throughputDataUnit;
    }

    public BigDecimal getThroughputDataSize() {
        return this.throughputDataSize;
    }

    public void setThroughputDataSize(BigDecimal throughputDataSize) {
        this.throughputDataSize = throughputDataSize;
    }

    public BigDecimal getThroughputThresholdValue() {
        return this.throughputThresholdValue;
    }

    public void setThroughputThresholdValue(BigDecimal throughputThresholdValue) {
        this.throughputThresholdValue = throughputThresholdValue;
    }

    public BigDecimal getAverageResponseTimeValue() {
        return this.averageResponseTimeValue;
    }

    public void setAverageResponseTimeValue(BigDecimal averageResponseTimeValue) {
        this.averageResponseTimeValue = averageResponseTimeValue;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("ServiceLevelObjective (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(validFrom);
        sb.append(", ").append(validTo);
        sb.append(", ").append(slaId);
        sb.append(", ").append(timeUnit);
        sb.append(", ").append(relationalOperator);
        sb.append(", ").append(sloTypeId);
        sb.append(", ").append(percentageOfAvailability);
        sb.append(", ").append(throughputDataUnit);
        sb.append(", ").append(throughputDataSize);
        sb.append(", ").append(throughputThresholdValue);
        sb.append(", ").append(averageResponseTimeValue);

        sb.append(")");
        return sb.toString();
    }
}
