/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.pojos;


import java.io.Serializable;
import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Sla implements Serializable {

    private static final long serialVersionUID = -1589049274;

    private Integer    id;
    private String     status;
    private BigDecimal servicePrice;
    private String     lifecyclePhase;
    private Date       validFrom;
    private Date       validTo;
    private Integer    serviceProviderId;
    private Integer    serviceCustomerId;

    public Sla() {}

    public Sla(Sla value) {
        this.id = value.id;
        this.status = value.status;
        this.servicePrice = value.servicePrice;
        this.lifecyclePhase = value.lifecyclePhase;
        this.validFrom = value.validFrom;
        this.validTo = value.validTo;
        this.serviceProviderId = value.serviceProviderId;
        this.serviceCustomerId = value.serviceCustomerId;
    }

    public Sla(
        Integer    id,
        String     status,
        BigDecimal servicePrice,
        String     lifecyclePhase,
        Date       validFrom,
        Date       validTo,
        Integer    serviceProviderId,
        Integer    serviceCustomerId
    ) {
        this.id = id;
        this.status = status;
        this.servicePrice = servicePrice;
        this.lifecyclePhase = lifecyclePhase;
        this.validFrom = validFrom;
        this.validTo = validTo;
        this.serviceProviderId = serviceProviderId;
        this.serviceCustomerId = serviceCustomerId;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public BigDecimal getServicePrice() {
        return this.servicePrice;
    }

    public void setServicePrice(BigDecimal servicePrice) {
        this.servicePrice = servicePrice;
    }

    public String getLifecyclePhase() {
        return this.lifecyclePhase;
    }

    public void setLifecyclePhase(String lifecyclePhase) {
        this.lifecyclePhase = lifecyclePhase;
    }

    public Date getValidFrom() {
        return this.validFrom;
    }

    public void setValidFrom(Date validFrom) {
        this.validFrom = validFrom;
    }

    public Date getValidTo() {
        return this.validTo;
    }

    public void setValidTo(Date validTo) {
        this.validTo = validTo;
    }

    public Integer getServiceProviderId() {
        return this.serviceProviderId;
    }

    public void setServiceProviderId(Integer serviceProviderId) {
        this.serviceProviderId = serviceProviderId;
    }

    public Integer getServiceCustomerId() {
        return this.serviceCustomerId;
    }

    public void setServiceCustomerId(Integer serviceCustomerId) {
        this.serviceCustomerId = serviceCustomerId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Sla (");

        sb.append(id);
        sb.append(", ").append(status);
        sb.append(", ").append(servicePrice);
        sb.append(", ").append(lifecyclePhase);
        sb.append(", ").append(validFrom);
        sb.append(", ").append(validTo);
        sb.append(", ").append(serviceProviderId);
        sb.append(", ").append(serviceCustomerId);

        sb.append(")");
        return sb.toString();
    }
}
