/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SlaUser implements Serializable {

    private static final long serialVersionUID = 1021393184;

    private Integer id;
    private String  password;
    private String  salt;
    private String  phoneNr;
    private String  username;
    private String  partyType;
    private String  partyName;

    public SlaUser() {}

    public SlaUser(SlaUser value) {
        this.id = value.id;
        this.password = value.password;
        this.salt = value.salt;
        this.phoneNr = value.phoneNr;
        this.username = value.username;
        this.partyType = value.partyType;
        this.partyName = value.partyName;
    }

    public SlaUser(
        Integer id,
        String  password,
        String  salt,
        String  phoneNr,
        String  username,
        String  partyType,
        String  partyName
    ) {
        this.id = id;
        this.password = password;
        this.salt = salt;
        this.phoneNr = phoneNr;
        this.username = username;
        this.partyType = partyType;
        this.partyName = partyName;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getSalt() {
        return this.salt;
    }

    public void setSalt(String salt) {
        this.salt = salt;
    }

    public String getPhoneNr() {
        return this.phoneNr;
    }

    public void setPhoneNr(String phoneNr) {
        this.phoneNr = phoneNr;
    }

    public String getUsername() {
        return this.username;
    }

    public void setUsername(String username) {
        this.username = username;
    }

    public String getPartyType() {
        return this.partyType;
    }

    public void setPartyType(String partyType) {
        this.partyType = partyType;
    }

    public String getPartyName() {
        return this.partyName;
    }

    public void setPartyName(String partyName) {
        this.partyName = partyName;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("SlaUser (");

        sb.append(id);
        sb.append(", ").append(password);
        sb.append(", ").append(salt);
        sb.append(", ").append(phoneNr);
        sb.append(", ").append(username);
        sb.append(", ").append(partyType);
        sb.append(", ").append(partyName);

        sb.append(")");
        return sb.toString();
    }
}
