/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.records;


import ch.uzh.slamer.model.tables.Sla;

import java.math.BigDecimal;
import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SlaRecord extends UpdatableRecordImpl<SlaRecord> implements Record8<Integer, String, BigDecimal, String, Date, Date, Integer, Integer> {

    private static final long serialVersionUID = 1353872633;

    /**
     * Setter for <code>public.sla.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sla.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.sla.status</code>.
     */
    public void setStatus(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sla.status</code>.
     */
    public String getStatus() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.sla.service_price</code>.
     */
    public void setServicePrice(BigDecimal value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sla.service_price</code>.
     */
    public BigDecimal getServicePrice() {
        return (BigDecimal) get(2);
    }

    /**
     * Setter for <code>public.sla.lifecycle_phase</code>.
     */
    public void setLifecyclePhase(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sla.lifecycle_phase</code>.
     */
    public String getLifecyclePhase() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sla.valid_from</code>.
     */
    public void setValidFrom(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sla.valid_from</code>.
     */
    public Date getValidFrom() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>public.sla.valid_to</code>.
     */
    public void setValidTo(Date value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.sla.valid_to</code>.
     */
    public Date getValidTo() {
        return (Date) get(5);
    }

    /**
     * Setter for <code>public.sla.service_provider_id</code>.
     */
    public void setServiceProviderId(Integer value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.sla.service_provider_id</code>.
     */
    public Integer getServiceProviderId() {
        return (Integer) get(6);
    }

    /**
     * Setter for <code>public.sla.service_customer_id</code>.
     */
    public void setServiceCustomerId(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.sla.service_customer_id</code>.
     */
    public Integer getServiceCustomerId() {
        return (Integer) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, BigDecimal, String, Date, Date, Integer, Integer> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, BigDecimal, String, Date, Date, Integer, Integer> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Sla.SLA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Sla.SLA.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<BigDecimal> field3() {
        return Sla.SLA.SERVICE_PRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Sla.SLA.LIFECYCLE_PHASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Sla.SLA.VALID_FROM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field6() {
        return Sla.SLA.VALID_TO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field7() {
        return Sla.SLA.SERVICE_PROVIDER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Sla.SLA.SERVICE_CUSTOMER_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal component3() {
        return getServicePrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getLifecyclePhase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getValidFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component6() {
        return getValidTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component7() {
        return getServiceProviderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getServiceCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public BigDecimal value3() {
        return getServicePrice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getLifecyclePhase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getValidFrom();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value6() {
        return getValidTo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value7() {
        return getServiceProviderId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getServiceCustomerId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaRecord value2(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaRecord value3(BigDecimal value) {
        setServicePrice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaRecord value4(String value) {
        setLifecyclePhase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaRecord value5(Date value) {
        setValidFrom(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaRecord value6(Date value) {
        setValidTo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaRecord value7(Integer value) {
        setServiceProviderId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaRecord value8(Integer value) {
        setServiceCustomerId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SlaRecord values(Integer value1, String value2, BigDecimal value3, String value4, Date value5, Date value6, Integer value7, Integer value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SlaRecord
     */
    public SlaRecord() {
        super(Sla.SLA);
    }

    /**
     * Create a detached, initialised SlaRecord
     */
    public SlaRecord(Integer id, String status, BigDecimal servicePrice, String lifecyclePhase, Date validFrom, Date validTo, Integer serviceProviderId, Integer serviceCustomerId) {
        super(Sla.SLA);

        set(0, id);
        set(1, status);
        set(2, servicePrice);
        set(3, lifecyclePhase);
        set(4, validFrom);
        set(5, validTo);
        set(6, serviceProviderId);
        set(7, serviceCustomerId);
    }
}
