/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.daos;


import ch.uzh.slamer.model.tables.Address;
import ch.uzh.slamer.model.tables.records.AddressRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AddressDao extends DAOImpl<AddressRecord, ch.uzh.slamer.model.tables.pojos.Address, Integer> {

    /**
     * Create a new AddressDao without any configuration
     */
    public AddressDao() {
        super(Address.ADDRESS, ch.uzh.slamer.model.tables.pojos.Address.class);
    }

    /**
     * Create a new AddressDao with an attached configuration
     */
    public AddressDao(Configuration configuration) {
        super(Address.ADDRESS, ch.uzh.slamer.model.tables.pojos.Address.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(ch.uzh.slamer.model.tables.pojos.Address object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Address> fetchById(Integer... values) {
        return fetch(Address.ADDRESS.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.uzh.slamer.model.tables.pojos.Address fetchOneById(Integer value) {
        return fetchOne(Address.ADDRESS.ID, value);
    }

    /**
     * Fetch records that have <code>postal_code IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Address> fetchByPostalCode(Integer... values) {
        return fetch(Address.ADDRESS.POSTAL_CODE, values);
    }

    /**
     * Fetch records that have <code>city IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Address> fetchByCity(String... values) {
        return fetch(Address.ADDRESS.CITY, values);
    }

    /**
     * Fetch records that have <code>street IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Address> fetchByStreet(String... values) {
        return fetch(Address.ADDRESS.STREET, values);
    }

    /**
     * Fetch records that have <code>street_nr IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Address> fetchByStreetNr(Integer... values) {
        return fetch(Address.ADDRESS.STREET_NR, values);
    }

    /**
     * Fetch records that have <code>user_id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Address> fetchByUserId(Integer... values) {
        return fetch(Address.ADDRESS.USER_ID, values);
    }
}
