/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.daos;


import ch.uzh.slamer.model.tables.ServiceLevelObjective;
import ch.uzh.slamer.model.tables.records.ServiceLevelObjectiveRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ServiceLevelObjectiveDao extends DAOImpl<ServiceLevelObjectiveRecord, ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective, Integer> {

    /**
     * Create a new ServiceLevelObjectiveDao without any configuration
     */
    public ServiceLevelObjectiveDao() {
        super(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE, ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective.class);
    }

    /**
     * Create a new ServiceLevelObjectiveDao with an attached configuration
     */
    public ServiceLevelObjectiveDao(Configuration configuration) {
        super(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE, ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchById(Integer... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective fetchOneById(Integer value) {
        return fetchOne(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.ID, value);
    }

    /**
     * Fetch records that have <code>name IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByName(String... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.NAME, values);
    }

    /**
     * Fetch records that have <code>valid_from IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByValidFrom(Date... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.VALID_FROM, values);
    }

    /**
     * Fetch records that have <code>valid_to IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByValidTo(Date... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.VALID_TO, values);
    }

    /**
     * Fetch records that have <code>sla_id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchBySlaId(Integer... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.SLA_ID, values);
    }

    /**
     * Fetch records that have <code>time_unit IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByTimeUnit(String... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.TIME_UNIT, values);
    }

    /**
     * Fetch records that have <code>relational_operator IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByRelationalOperator(String... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.RELATIONAL_OPERATOR, values);
    }

    /**
     * Fetch records that have <code>slo_type_id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchBySloTypeId(Integer... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.SLO_TYPE_ID, values);
    }

    /**
     * Fetch records that have <code>percentage_of_availability IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByPercentageOfAvailability(BigDecimal... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.PERCENTAGE_OF_AVAILABILITY, values);
    }

    /**
     * Fetch records that have <code>throughput_data_unit IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByThroughputDataUnit(String... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.THROUGHPUT_DATA_UNIT, values);
    }

    /**
     * Fetch records that have <code>throughput_data_size IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByThroughputDataSize(BigDecimal... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.THROUGHPUT_DATA_SIZE, values);
    }

    /**
     * Fetch records that have <code>throughput_threshold_value IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByThroughputThresholdValue(BigDecimal... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.THROUGHPUT_THRESHOLD_VALUE, values);
    }

    /**
     * Fetch records that have <code>average_response_time_value IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.ServiceLevelObjective> fetchByAverageResponseTimeValue(BigDecimal... values) {
        return fetch(ServiceLevelObjective.SERVICE_LEVEL_OBJECTIVE.AVERAGE_RESPONSE_TIME_VALUE, values);
    }
}
