/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.daos;


import ch.uzh.slamer.model.tables.Sla;
import ch.uzh.slamer.model.tables.records.SlaRecord;

import java.math.BigDecimal;
import java.sql.Date;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SlaDao extends DAOImpl<SlaRecord, ch.uzh.slamer.model.tables.pojos.Sla, Integer> {

    /**
     * Create a new SlaDao without any configuration
     */
    public SlaDao() {
        super(Sla.SLA, ch.uzh.slamer.model.tables.pojos.Sla.class);
    }

    /**
     * Create a new SlaDao with an attached configuration
     */
    public SlaDao(Configuration configuration) {
        super(Sla.SLA, ch.uzh.slamer.model.tables.pojos.Sla.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(ch.uzh.slamer.model.tables.pojos.Sla object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Sla> fetchById(Integer... values) {
        return fetch(Sla.SLA.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.uzh.slamer.model.tables.pojos.Sla fetchOneById(Integer value) {
        return fetchOne(Sla.SLA.ID, value);
    }

    /**
     * Fetch records that have <code>status IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Sla> fetchByStatus(String... values) {
        return fetch(Sla.SLA.STATUS, values);
    }

    /**
     * Fetch records that have <code>service_price IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Sla> fetchByServicePrice(BigDecimal... values) {
        return fetch(Sla.SLA.SERVICE_PRICE, values);
    }

    /**
     * Fetch records that have <code>lifecycle_phase IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Sla> fetchByLifecyclePhase(String... values) {
        return fetch(Sla.SLA.LIFECYCLE_PHASE, values);
    }

    /**
     * Fetch records that have <code>valid_from IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Sla> fetchByValidFrom(Date... values) {
        return fetch(Sla.SLA.VALID_FROM, values);
    }

    /**
     * Fetch records that have <code>valid_to IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Sla> fetchByValidTo(Date... values) {
        return fetch(Sla.SLA.VALID_TO, values);
    }

    /**
     * Fetch records that have <code>service_provider_id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Sla> fetchByServiceProviderId(Integer... values) {
        return fetch(Sla.SLA.SERVICE_PROVIDER_ID, values);
    }

    /**
     * Fetch records that have <code>service_customer_id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.Sla> fetchByServiceCustomerId(Integer... values) {
        return fetch(Sla.SLA.SERVICE_CUSTOMER_ID, values);
    }
}
