/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.daos;


import ch.uzh.slamer.model.tables.SlaUser;
import ch.uzh.slamer.model.tables.records.SlaUserRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SlaUserDao extends DAOImpl<SlaUserRecord, ch.uzh.slamer.model.tables.pojos.SlaUser, Integer> {

    /**
     * Create a new SlaUserDao without any configuration
     */
    public SlaUserDao() {
        super(SlaUser.SLA_USER, ch.uzh.slamer.model.tables.pojos.SlaUser.class);
    }

    /**
     * Create a new SlaUserDao with an attached configuration
     */
    public SlaUserDao(Configuration configuration) {
        super(SlaUser.SLA_USER, ch.uzh.slamer.model.tables.pojos.SlaUser.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(ch.uzh.slamer.model.tables.pojos.SlaUser object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.SlaUser> fetchById(Integer... values) {
        return fetch(SlaUser.SLA_USER.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.uzh.slamer.model.tables.pojos.SlaUser fetchOneById(Integer value) {
        return fetchOne(SlaUser.SLA_USER.ID, value);
    }

    /**
     * Fetch records that have <code>password IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.SlaUser> fetchByPassword(String... values) {
        return fetch(SlaUser.SLA_USER.PASSWORD, values);
    }

    /**
     * Fetch records that have <code>salt IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.SlaUser> fetchBySalt(String... values) {
        return fetch(SlaUser.SLA_USER.SALT, values);
    }

    /**
     * Fetch records that have <code>phone_nr IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.SlaUser> fetchByPhoneNr(String... values) {
        return fetch(SlaUser.SLA_USER.PHONE_NR, values);
    }

    /**
     * Fetch records that have <code>username IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.SlaUser> fetchByUsername(String... values) {
        return fetch(SlaUser.SLA_USER.USERNAME, values);
    }

    /**
     * Fetch records that have <code>party_type IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.SlaUser> fetchByPartyType(String... values) {
        return fetch(SlaUser.SLA_USER.PARTY_TYPE, values);
    }

    /**
     * Fetch records that have <code>party_name IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.SlaUser> fetchByPartyName(String... values) {
        return fetch(SlaUser.SLA_USER.PARTY_NAME, values);
    }
}
