/*
 * This file is generated by jOOQ.
 */
package ch.uzh.slamer.model.tables.daos;


import ch.uzh.slamer.model.tables.SloType;
import ch.uzh.slamer.model.tables.records.SloTypeRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SloTypeDao extends DAOImpl<SloTypeRecord, ch.uzh.slamer.model.tables.pojos.SloType, Integer> {

    /**
     * Create a new SloTypeDao without any configuration
     */
    public SloTypeDao() {
        super(SloType.SLO_TYPE, ch.uzh.slamer.model.tables.pojos.SloType.class);
    }

    /**
     * Create a new SloTypeDao with an attached configuration
     */
    public SloTypeDao(Configuration configuration) {
        super(SloType.SLO_TYPE, ch.uzh.slamer.model.tables.pojos.SloType.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(ch.uzh.slamer.model.tables.pojos.SloType object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.SloType> fetchById(Integer... values) {
        return fetch(SloType.SLO_TYPE.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public ch.uzh.slamer.model.tables.pojos.SloType fetchOneById(Integer value) {
        return fetchOne(SloType.SLO_TYPE.ID, value);
    }

    /**
     * Fetch records that have <code>type IN (values)</code>
     */
    public List<ch.uzh.slamer.model.tables.pojos.SloType> fetchByType(String... values) {
        return fetch(SloType.SLO_TYPE.TYPE, values);
    }
}
